import {
  AssetsPage,
  BankAccounts,
  CashInHand,
  CementOrderDispatched,
  CementPurchaseOrder,
  CompleteBill,
  ExpensePage,
  FundTransfer,
  GoodsTransfer,
  HomePage,
  ItemPage,
  OtherIncomePage,
  P2PTrasnfer,
  PartyConfirmation,
  PartyPage,
  PaymentIn,
  PaymentOut,
  PriceListPage,
  PurchaseBill,
  PurchaseOrder,
  PurchaseReturn,
  RecycleBin,
  ReportPage,
  SaleBill,
  SaleOrder,
  SaleReturn,
  Setup,
  TaskTodoPage,
  UserSetup,
  UserLog,
  Import,
  Export,
  Backup,
  PurchasePage,
  SalesPage,
  PaymentPage,
  CashAndBankPage,
  B2BTransactionPage,
  CementBookPage,
  UtilityPage,
  Users,
  RolesAndPermission,
  WareHouses,
} from '../pages';
import EditPermissions from '../pages/GeneralSettings/EditPermissions';

export const componentMap = {
  '/home': <HomePage />,
  '/parties': <PartyPage />,
  '/items': <ItemPage />,
  '/reports': <ReportPage />,
  '/price-list': <PriceListPage />,
  '/task-todo-list': <TaskTodoPage />,
  '/expenses': <ExpensePage />,
  '/other-income': <OtherIncomePage />,
  '/assets-directory': <AssetsPage />,
  '/purchase': <PurchasePage />,
  '/purchase/purchase-order': <PurchaseOrder />,
  '/purchase/purchase-bill': <PurchaseBill />,
  '/purchase/purchase-return-or-debit-note': <PurchaseReturn />,
  '/sale': <SalesPage />,
  '/sale/sale-order': <SaleOrder />,
  '/sale/sale-bill': <SaleBill />,
  '/sale/sale-return-or-credit-note': <SaleReturn />,
  '/payment': <PaymentPage />,
  '/payment/payment-in': <PaymentIn />,
  '/payment/payment-out': <PaymentOut />,
  '/cash-bank': <CashAndBankPage />,
  '/cash-bank/cash-in-hand': <CashInHand />,
  '/cash-bank/bank-accounts': <BankAccounts />,
  '/cash-bank/p2p-transfer': <P2PTrasnfer />,
  '/b2b-transaction': <B2BTransactionPage />,
  '/b2b-transaction/goods-transfer': <GoodsTransfer />,
  '/b2b-transaction/fund-transfer': <FundTransfer />,
  '/cement-book': <CementBookPage />,
  '/cement-book/purchase-order': <CementPurchaseOrder />,
  '/cement-book/order-dispatched': <CementOrderDispatched />,
  '/cement-book/party-confirmation': <PartyConfirmation />,
  '/cement-book/complete-bill': <CompleteBill />,
  '/utility': <UtilityPage />,
  '/utility/user-setup': <UserSetup />,
  '/utility/setup': <Setup />,
  '/utility/recycle-bin': <RecycleBin />,
  '/utility/user-log': <UserLog />,
  '/utility/import': <Import />,
  '/utility/export': <Export />,
  '/utility/backup-data-to-drive': <Backup />,
  '/general-settings/warehouses': <WareHouses />,
  '/general-settings/roles-permissions': <RolesAndPermission />,
  '/general-settings/EditPermissions': <EditPermissions />,
  '/general-settings/users': <Users />,
};
